// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationBot.DataAccess;

#nullable disable

namespace NotificationBot.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NotificationBot.DataAccess.Entities.CryptoAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoinGeckoAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CryptoAssets");
                });

            modelBuilder.Entity("NotificationBot.DataAccess.Entities.FavoriteCryptoAsset", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("CryptoAssetId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "CryptoAssetId");

                    b.HasIndex("CryptoAssetId");

                    b.ToTable("FavoriteCryptoAssets", (string)null);
                });

            modelBuilder.Entity("NotificationBot.DataAccess.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NotificationBot.DataAccess.Entities.FavoriteCryptoAsset", b =>
                {
                    b.HasOne("NotificationBot.DataAccess.Entities.CryptoAsset", "CryptoAsset")
                        .WithMany("FavoriteCryptoAssets")
                        .HasForeignKey("CryptoAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationBot.DataAccess.Entities.User", "User")
                        .WithMany("FavoriteCryptoAssets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoAsset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotificationBot.DataAccess.Entities.CryptoAsset", b =>
                {
                    b.Navigation("FavoriteCryptoAssets");
                });

            modelBuilder.Entity("NotificationBot.DataAccess.Entities.User", b =>
                {
                    b.Navigation("FavoriteCryptoAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
